"use client";
import { Rufina, Playfair_Display, Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";

import Footer from "@/components/common/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect } from "react";
import { useRouter } from "next/navigation";



// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const rufina = Rufina({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rufina",
});

const playfair = Playfair_Display({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-platfair",
});

const raleway = Raleway({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-raleway",
});


// export const metadata = {
//   title: "Luxury Rental ",
//   description: "Generated by create next app",
// };

// Create a client
const queryClient = new QueryClient();

export default function RootLayout({ children }) {
  const router = useRouter();

  useEffect(() => {
    const user  = localStorage.getItem("email");
    if (!user) {
      router.push("/login")
    } 
    },[])
    
  return (
    <html lang="en">
      <body
        className={`${rufina.variable}  ${playfair.variable} ${raleway.variable} antialiased`}
      >
        <>
        <QueryClientProvider  client={queryClient}>
          <Header />

          {children}
          <ToastContainer />
          <Footer />
          </QueryClientProvider>
        </>
      </body>
    </html>
  );
}
