import { Rufina, Playfair_Display, Raleway} from 'next/font/google'
import "./globals.css";
import Header from "@/components/common/Header";

import Footer from '@/components/common/Footer';
import Hero from '@/components/home/Hero';
import Villas from '@/components/home/Villas';
import Region from '@/components/home/Region';
import Speciality from '@/components/home/Speciality';
import Host from '@/components/home/Host';
import About from '@/components/home/About';
import Scene from '@/components/home/Scene';



// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const rufina = Rufina({
  weight: ['400', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display : 'swap',
  variable: '--font-rufina',
 
})

const playfair = Playfair_Display({
  weight: ['400'],
  subsets: ['latin'],
  display : 'swap',
  variable: '--font-platfair',
})

const raleway = Raleway({
  weight: ['400', '700'],
  subsets: ['latin'],
  display : 'swap',
  variable: '--font-raleway',
})

export const metadata = {
  title: "Luxury Rental ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${rufina.variable}  ${playfair.variable} ${raleway.variable} antialiased`}
      >
        <>
        <Header/>

        <Hero/>
        <Villas/>
        <Region/>
        <Speciality/>
        <Host/>
        <About/>
        <Scene/>
     
        <Footer/>
        {children}
        </>
      </body>
    </html>
  );
}
